// Generated by TKG at 2017-08-08 23:56:26

// #include "keymap_common.h"
#include "xd60.h"
#include "action_layer.h"

// tap dance declaration
enum {
  TD_SL_RS = 0
};

// tap dance definition
qk_tap_dance_action_t tap_dance_actions[] = {
  [TD_SL_RS] = ACTION_TAP_DANCE_DOUBLE(KC_SLSH, KC_RSFT) // tap dance /? && RSFT
};

#define KEYMAP_TKG( \
    K0A, K0B, K0C, K0D, K0E, K0F, K0G, K0H, K0I, K0J, K0K, K0L, K0M, K0N, \
    K1A, K1B, K1C, K1D, K1E, K1F, K1G, K1H, K1I, K1J, K1K, K1L, K1M, K1N, \
    K2A, K2B, K2C, K2D, K2E, K2F, K2G, K2H, K2I, K2J, K2K, K2L,      K2N, \
    K3A,      K3C, K3D, K3E, K3F, K3G, K3H, K3I, K3J, K3K,      K3M, K3N, \
    K4A, K4B, K4C,           K4F,      K4H, K4I,      K4K, K4L, K4M, K4N  \
) { \
    { KC_##K0A, KC_##K0B, KC_##K0C, KC_##K0D, KC_##K0E, KC_##K0F, KC_##K0G, KC_##K0H, KC_##K0I, KC_##K0J, KC_##K0K, KC_##K0L, KC_##K0M, KC_##K0N }, \
    { KC_##K1A, KC_##K1B, KC_##K1C, KC_##K1D, KC_##K1E, KC_##K1F, KC_##K1G, KC_##K1H, KC_##K1I, KC_##K1J, KC_##K1K, KC_##K1L, KC_##K1M, KC_##K1N }, \
    { KC_##K2A, KC_##K2B, KC_##K2C, KC_##K2D, KC_##K2E, KC_##K2F, KC_##K2G, KC_##K2H, KC_##K2I, KC_##K2J, KC_##K2K, KC_##K2L, KC_NO,    KC_##K2N }, \
    { KC_##K3A, KC_NO,    KC_##K3C, KC_##K3D, KC_##K3E, KC_##K3F, KC_##K3G, KC_##K3H, KC_##K3I, KC_##K3J, KC_##K3K, KC_NO,    KC_##K3M, KC_##K3N }, \
    { KC_##K4A, KC_##K4B, KC_##K4C, KC_NO,    KC_NO,    KC_##K4F, KC_NO,    KC_##K4H, KC_##K4I, KC_NO,    KC_##K4K, KC_##K4L, KC_##K4M, KC_##K4N }  \
}

// #ifdef KEYMAP_SECTION_ENABLE
// const uint8_t keymaps[][MATRIX_ROWS][MATRIX_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
// #else
const uint16_t keymaps[][MATRIX_ROWS][MATRIX_COLS] PROGMEM = {
// #endif
    // 0: Base layer
    KEYMAP(
        KC_ESC,  KC_1,    KC_2,   KC_3,   KC_4,    KC_5,   KC_6,    KC_7,   KC_8,    KC_9,   KC_0,    KC_MINS,  KC_EQL,  KC_BSPC, KC_NO, \
        KC_TAB,  KC_Q,    KC_W,   KC_E,   KC_R,    KC_T,   KC_Y,    KC_U,   KC_I,    KC_O,   KC_P,    KC_LBRC,  KC_RBRC,          KC_BSLS, \
        KC_CAPS, KC_A,    KC_S,   KC_D,   KC_F,    KC_G,   KC_H,    KC_J,   KC_K,    KC_L,   KC_SCLN, KC_QUOT,  KC_NO,            KC_ENT,  \
        KC_LSFT, KC_NO,   KC_Z,   KC_X,   KC_C,    KC_V,   KC_B,    KC_N,   KC_M,    KC_COMM,KC_DOT,  KC_NO,    TD(TD_SL_RS), KC_UP,   KC_DEL,  \
        KC_LCTL, KC_LGUI, KC_LALT,                         KC_SPC,                           KC_SLSH, F(0),     KC_LEFT, KC_DOWN, KC_RGHT),
    // 1: Function layer
    KEYMAP(
        KC_GRV,  KC_F1,   KC_F2,  KC_F3,  KC_F4,   KC_F5,  KC_F6,   KC_F7,  KC_F8,   KC_F9,  KC_F10,  KC_F11,   KC_F12,  KC_DEL,  KC_NO,  \
        KC_NO,   BL_TOGG, BL_DEC, BL_INC, BL_STEP, KC_NO,  KC_CALC, KC_NO,  KC_NO,   KC_INS, KC_HOME, KC_PGUP,  KC_PAUS,          KC_PSCR, \
        KC_NO,   KC_MUTE, KC_VOLD,KC_VOLU,KC_NO,   KC_NO,  KC_NO,   KC_NO,  KC_NO,   KC_DEL, KC_END,  KC_PGDN,  KC_NO,            KC_NO, \
        KC_NO,   KC_NO,   KC_APP,  RGB_TOG,RGB_MOD,RGB_HUD, RGB_HUI,RGB_SAD, RGB_SAI,RGB_VAD, RGB_VAI,KC_NO,    KC_NO,   KC_PGUP, KC_NO,\
        KC_NO,   KC_NO,   KC_NO,                           KC_NO,                            KC_NO,   F(0),     KC_HOME, KC_PGDN, KC_END),
};

// #ifdef KEYMAP_SECTION_ENABLE
// const uint16_t fn_actions[] __attribute__ ((section (".keymap.fn_actions"))) = {
// #else
// const uint16_t fn_actions[] PROGMEM = {
// #endif
const uint16_t PROGMEM fn_actions[] = {
    [0] = ACTION_LAYER_MOMENTARY(1),
};
